### ISSUE TITLE
Unable to remove specific arg

### ISSUE THREAD

**Issue by erik-stephens** [rhboot/grubby#23]
For args like `console` where there can be multiple instances, --remove-args will remove the first instance with matching param name.  I'd like to be able to remove the specific instance.  Is that possible?  Thanks!

```
# grubby --info $k | grep args | tr ' ' '\n' | grep console
console=tty1
console=ttyS1,115200n"

# grubby --update-kernel $k --remove-args console=ttyS1,115200n

# grubby --info $k | grep args | tr ' ' '\n' | grep console
console=ttyS1,115200n"
```

**Comment by nbrewk** [comment]
I wanted to chime in on this. I have a E485 laptop that requires specific arguments to be able to boot. I used grubby to add arguments several times over based on what I was finding online, so duplicate entries resulted.

My workaround was edit each indvidual .conf file under /boot/loader/entries with nano as sudo. After you get rid of all duplicate arguments, grubby then parses them correctly. That is, add the argument you want through grubby after.

I would say the issue is that grubby won't have a problem appending duplicate args, but gets confused when multiple duplicate arguments exist for a given kernel entry. The man page states that arguments are to be entered as quoted and space-separated, so when a string is identical to what is seen as an argument, this isn't parsed correctly.

In my search for a solution, I've seen the issue crop up over the years but never really addressed. Hopefully, this helps someone else in a few years!

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
